\LoadClass[twocolumn]{extarticle}

\usepackage{algorithm,algorithmic,amsfonts,amssymb,amsthm,bm,booktabs,cancel,caption,centernot,dsfont,graphicx,marvosym,mathtools,microtype,nicefrac,physics,stackengine,subcaption,textcomp,tikz,xcolor,xparse}
\usepackage[a4paper,columnsep=0.5cm,margin=0.5cm]{geometry}
\usepackage[bb=boondox,cal=esstix,scr=boondox]{mathalpha}

\usepackage{enumitem}
\setlist{nosep}

\usepackage{parskip}
\makeatletter\def\thm@space@setup{\thm@preskip=0pt\thm@postskip=0pt}\makeatother

\usepackage{setspace}
\setstretch{1}

\usepackage{times}
\makeatletter\renewcommand\normalsize{\@setfontsize\normalsize{6}{7}}\normalsize\makeatother

\pagenumbering{gobble}

\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
